
# Sets up Java Development Kit (JDK) 17
# Builds the project using Maven
# Builds a Docker image from the Dockerfile
name: A workflow for my Hello World App

on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-22.04

    steps:
      # Checkout the code from the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Build the project and create a package using Maven
      - name: Package with Maven
        run: mvn package

      # Build the Docker image using the Dockerfile in the repo
      - name: Build Docker Image
        run: docker build -t devopsimage .

      - name: Run image
        run: docker run --name devopscontainer -d devopsimage

      - name: View logs
        run: docker logs devopscontainer


